# First remove *all* keybindings
unbind-key -a
# Now reinsert all the regular tmux keys
bind ^X lock-server
bind o new-window
bind d detach
bind w list-windows
bind m resize-pane -Z
bind a last-window
#
bind p previous-window
bind n next-window
#
# Window switching by number
bind 1 select-window -t 1
bind 2 select-window -t 2
bind 3 select-window -t 3
bind 4 select-window -t 4
bind 5 select-window -t 5
bind 6 select-window -t 6
bind 7 select-window -t 7
bind 8 select-window -t 8
bind 9 select-window -t 9
#
bind s display-popup -E -w 60% -h 50% -b rounded -S "fg=#cdd6f4,bg=#1e1e2e" -T " Switch Session " "tmux list-sessions -F '#{session_name}' | fzf --reverse --prompt='  ' | xargs tmux switch-client -t"
bind S choose-session
# bind r command-prompt "rename-window %%"
bind R source-file ~/.tmux.conf
bind - split-window -v
bind | split-window -h
bind '"' choose-window
bind -n C-o display-popup -E -w 60% -h 50% -b rounded -S "fg=#cdd6f4,bg=#1e1e2e" -T " Sessions " "~/.local/bin/jtpop"
bind [ copy-mode
bind Escape copy-mode
bind -r -T prefix h resize-pane -L 20
bind -r -T prefix l resize-pane -R 20
bind -r -T prefix j resize-pane -D 7
bind -r -T prefix k resize-pane -U 7
bind : command-prompt
bind B set pane-border-status
bind * setw synchronize-panes
bind x confirm-before kill-pane
bind e swap-pane -D
bind K send-keys "clear"\; send-keys "Enter"
